/**
 * Tests for the sidebar's copilot handling — permanent regression net for:
 *   1. `copilot` must appear in the provider dropdown HTML (first position).
 *   2. `hasConfig` must be true when {provider:'copilot', hasApiKey:false}
 *      so Step 2 unlocks (the "stuck on Step 1" bug).
 *   3. The webview must NOT show an "API key required" warning for copilot.
 *
 * The sidebar HTML is generated by `getSidebarHtml`, which is not exported.
 * We grep the source for the literal predicates so regressions cannot
 * silently slip back in.
 */
import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

const SIDEBAR_SOURCE = fs.readFileSync(
  path.join(__dirname, '..', 'sidebar-provider.ts'),
  'utf8',
);

describe('sidebar — copilot dropdown rendering', () => {
  it('webview provider list includes "copilot"', () => {
    expect(SIDEBAR_SOURCE).toContain("'copilot'");
    expect(SIDEBAR_SOURCE).toMatch(/for \(const p of \[[^\]]*'copilot'[^\]]*\]/);
  });

  it('copilot comes before anthropic in the dropdown (first option)', () => {
    const match = /for \(const p of \[([^\]]+)\]/.exec(SIDEBAR_SOURCE);
    expect(match).not.toBeNull();
    const providerList = match![1] ?? '';
    const copilotIdx = providerList.indexOf("'copilot'");
    const anthropicIdx = providerList.indexOf("'anthropic'");
    expect(copilotIdx).toBeGreaterThan(-1);
    expect(anthropicIdx).toBeGreaterThan(-1);
    expect(copilotIdx).toBeLessThan(anthropicIdx);
  });

  it('API_KEY_URLS table contains a copilot entry so dropdown change does not crash', () => {
    expect(SIDEBAR_SOURCE).toMatch(/copilot:\s*''/);
  });

  it('renderStep1 treats copilot like ollama (no API-key field shown)', () => {
    expect(SIDEBAR_SOURCE).toMatch(
      /isOllama\s*=\s*cfg\.provider\s*===\s*'ollama'\s*\|\|\s*cfg\.provider\s*===\s*'copilot'/,
    );
  });

  it('renderConfigSummary suppresses "no key" warning for copilot', () => {
    expect(SIDEBAR_SOURCE).toMatch(
      /isOllama\s*=\s*provider\s*===\s*'ollama'\s*\|\|\s*provider\s*===\s*'copilot'/,
    );
  });

  it('saveConfig allows copilot without an API key', () => {
    expect(SIDEBAR_SOURCE).toMatch(
      /provider\s*!==\s*'ollama'\s*&&\s*provider\s*!==\s*'copilot'\s*&&\s*!apiKey/,
    );
  });
});

describe('sidebar — hasConfig predicate (Step 2 unlock)', () => {
  // Mirrors the predicate in pushState(): "the user has a usable config when
  // an API key is set OR they picked a keyless provider".
  function hasConfig(info: { provider: string; hasApiKey: boolean } | null): boolean {
    if (info === null) return false;
    return info.hasApiKey || info.provider === 'ollama' || info.provider === 'copilot';
  }

  it('returns false when no config exists', () => {
    expect(hasConfig(null)).toBe(false);
  });

  it('returns true for anthropic with an API key', () => {
    expect(hasConfig({ provider: 'anthropic', hasApiKey: true })).toBe(true);
  });

  it('returns false for anthropic without an API key', () => {
    expect(hasConfig({ provider: 'anthropic', hasApiKey: false })).toBe(false);
  });

  it('returns true for ollama without an API key', () => {
    expect(hasConfig({ provider: 'ollama', hasApiKey: false })).toBe(true);
  });

  it('returns true for copilot without an API key — the original Step 2 bug', () => {
    expect(hasConfig({ provider: 'copilot', hasApiKey: false })).toBe(true);
  });

  it('source still encodes the same predicate (drift guard)', () => {
    // If someone removes the "|| copilot" branch the sidebar will silently get stuck again.
    expect(SIDEBAR_SOURCE).toMatch(
      /configInfo\.hasApiKey\s*\|\|\s*configInfo\.provider\s*===\s*'ollama'\s*\|\|\s*configInfo\.provider\s*===\s*'copilot'/,
    );
  });
});
